#!/usr/bin/env python3

import os
import piplot.main

if __name__ == "__main__":
    if os.getuid() != 0:
        print("You need root permissions to do this ...")
        exit(1)
    piplot.main.main()
