#!/usr/bin/env python3

import os, sys
import piplot.main

if __name__ == "__main__":
    if os.getuid() != 0:
        print("You need root permissions to do this ...")
        sys.exit(1)
    piplot.main.main()
